// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: protocol/game.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Room Management
type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MaxPlayers    int32                  `protobuf:"varint,2,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_protocol_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoomRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoomRequest) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_protocol_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoomResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateRoomResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsRequest) Reset() {
	*x = ListRoomsRequest{}
	mi := &file_protocol_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsRequest) ProtoMessage() {}

func (x *ListRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsRequest.ProtoReflect.Descriptor instead.
func (*ListRoomsRequest) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{2}
}

type RoomInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Max           int32                  `protobuf:"varint,4,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_protocol_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{3}
}

func (x *RoomInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomInfo) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *RoomInfo) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type ListRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RoomInfo            `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsResponse) Reset() {
	*x = ListRoomsResponse{}
	mi := &file_protocol_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsResponse) ProtoMessage() {}

func (x *ListRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsResponse.ProtoReflect.Descriptor instead.
func (*ListRoomsResponse) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{4}
}

func (x *ListRoomsResponse) GetRooms() []*RoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_protocol_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{5}
}

func (x *JoinRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_protocol_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{6}
}

func (x *JoinResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *JoinResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JoinResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type LeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	mi := &file_protocol_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{7}
}

type LeaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveResponse) Reset() {
	*x = LeaveResponse{}
	mi := &file_protocol_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveResponse) ProtoMessage() {}

func (x *LeaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveResponse.ProtoReflect.Descriptor instead.
func (*LeaveResponse) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{8}
}

func (x *LeaveResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LeaveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Player State & Movement
type Vector3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	mi := &file_protocol_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{9}
}

func (x *Vector3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Quaternion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	W             float32                `protobuf:"fixed32,4,opt,name=w,proto3" json:"w,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quaternion) Reset() {
	*x = Quaternion{}
	mi := &file_protocol_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quaternion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quaternion) ProtoMessage() {}

func (x *Quaternion) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quaternion.ProtoReflect.Descriptor instead.
func (*Quaternion) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{10}
}

func (x *Quaternion) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Quaternion) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Quaternion) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Quaternion) GetW() float32 {
	if x != nil {
		return x.W
	}
	return 0
}

type PlayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Position      *Vector3               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Rotation      *Quaternion            `protobuf:"bytes,3,opt,name=rotation,proto3" json:"rotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_protocol_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{11}
}

func (x *PlayerState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerState) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PlayerState) GetRotation() *Quaternion {
	if x != nil {
		return x.Rotation
	}
	return nil
}

type MoveRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Position        *Vector3               `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Rotation        *Quaternion            `protobuf:"bytes,2,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Speed           float32                `protobuf:"fixed32,3,opt,name=speed,proto3" json:"speed,omitempty"`
	IsGrounded      bool                   `protobuf:"varint,4,opt,name=is_grounded,json=isGrounded,proto3" json:"is_grounded,omitempty"`
	ClientTimestamp int64                  `protobuf:"varint,5,opt,name=client_timestamp,json=clientTimestamp,proto3" json:"client_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_protocol_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{12}
}

func (x *MoveRequest) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *MoveRequest) GetRotation() *Quaternion {
	if x != nil {
		return x.Rotation
	}
	return nil
}

func (x *MoveRequest) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *MoveRequest) GetIsGrounded() bool {
	if x != nil {
		return x.IsGrounded
	}
	return false
}

func (x *MoveRequest) GetClientTimestamp() int64 {
	if x != nil {
		return x.ClientTimestamp
	}
	return 0
}

type MoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Position      *Vector3               `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"` // Server-confirmed position
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	mi := &file_protocol_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{13}
}

func (x *MoveResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MoveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MoveResponse) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

// Chat (Existing)
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"` // Can be empty when sending, filled by server
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_protocol_game_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{14}
}

func (x *ChatMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// Server Push Messages
type PlayerJoinPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerJoinPush) Reset() {
	*x = PlayerJoinPush{}
	mi := &file_protocol_game_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerJoinPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoinPush) ProtoMessage() {}

func (x *PlayerJoinPush) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoinPush.ProtoReflect.Descriptor instead.
func (*PlayerJoinPush) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{15}
}

func (x *PlayerJoinPush) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerJoinPush) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PlayerLeavePush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeavePush) Reset() {
	*x = PlayerLeavePush{}
	mi := &file_protocol_game_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeavePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeavePush) ProtoMessage() {}

func (x *PlayerLeavePush) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeavePush.ProtoReflect.Descriptor instead.
func (*PlayerLeavePush) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{16}
}

func (x *PlayerLeavePush) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PlayerMovePush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Position      *Vector3               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Rotation      *Quaternion            `protobuf:"bytes,3,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Speed         float32                `protobuf:"fixed32,4,opt,name=speed,proto3" json:"speed,omitempty"`
	IsGrounded    bool                   `protobuf:"varint,5,opt,name=is_grounded,json=isGrounded,proto3" json:"is_grounded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerMovePush) Reset() {
	*x = PlayerMovePush{}
	mi := &file_protocol_game_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMovePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMovePush) ProtoMessage() {}

func (x *PlayerMovePush) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMovePush.ProtoReflect.Descriptor instead.
func (*PlayerMovePush) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{17}
}

func (x *PlayerMovePush) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerMovePush) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PlayerMovePush) GetRotation() *Quaternion {
	if x != nil {
		return x.Rotation
	}
	return nil
}

func (x *PlayerMovePush) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *PlayerMovePush) GetIsGrounded() bool {
	if x != nil {
		return x.IsGrounded
	}
	return false
}

type ForcePositionPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Vector3               `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Rotation      *Quaternion            `protobuf:"bytes,2,opt,name=rotation,proto3" json:"rotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForcePositionPush) Reset() {
	*x = ForcePositionPush{}
	mi := &file_protocol_game_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForcePositionPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForcePositionPush) ProtoMessage() {}

func (x *ForcePositionPush) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForcePositionPush.ProtoReflect.Descriptor instead.
func (*ForcePositionPush) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{18}
}

func (x *ForcePositionPush) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *ForcePositionPush) GetRotation() *Quaternion {
	if x != nil {
		return x.Rotation
	}
	return nil
}

// Combat
type SkillInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       int32                  `protobuf:"varint,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Direction     *Vector3               `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillInfo) Reset() {
	*x = SkillInfo{}
	mi := &file_protocol_game_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillInfo) ProtoMessage() {}

func (x *SkillInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillInfo.ProtoReflect.Descriptor instead.
func (*SkillInfo) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{19}
}

func (x *SkillInfo) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *SkillInfo) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *SkillInfo) GetDirection() *Vector3 {
	if x != nil {
		return x.Direction
	}
	return nil
}

func (x *SkillInfo) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type CastSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillInfo     *SkillInfo             `protobuf:"bytes,1,opt,name=skill_info,json=skillInfo,proto3" json:"skill_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CastSkillRequest) Reset() {
	*x = CastSkillRequest{}
	mi := &file_protocol_game_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastSkillRequest) ProtoMessage() {}

func (x *CastSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastSkillRequest.ProtoReflect.Descriptor instead.
func (*CastSkillRequest) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{20}
}

func (x *CastSkillRequest) GetSkillInfo() *SkillInfo {
	if x != nil {
		return x.SkillInfo
	}
	return nil
}

type CastSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CastSkillResponse) Reset() {
	*x = CastSkillResponse{}
	mi := &file_protocol_game_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastSkillResponse) ProtoMessage() {}

func (x *CastSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastSkillResponse.ProtoReflect.Descriptor instead.
func (*CastSkillResponse) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{21}
}

func (x *CastSkillResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CastSkillResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SkillCastPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CasterId      string                 `protobuf:"bytes,1,opt,name=caster_id,json=casterId,proto3" json:"caster_id,omitempty"`
	SkillInfo     *SkillInfo             `protobuf:"bytes,2,opt,name=skill_info,json=skillInfo,proto3" json:"skill_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillCastPush) Reset() {
	*x = SkillCastPush{}
	mi := &file_protocol_game_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillCastPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillCastPush) ProtoMessage() {}

func (x *SkillCastPush) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillCastPush.ProtoReflect.Descriptor instead.
func (*SkillCastPush) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{22}
}

func (x *SkillCastPush) GetCasterId() string {
	if x != nil {
		return x.CasterId
	}
	return ""
}

func (x *SkillCastPush) GetSkillInfo() *SkillInfo {
	if x != nil {
		return x.SkillInfo
	}
	return nil
}

type AttributeUpdatePush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Damage        int32                  `protobuf:"varint,2,opt,name=damage,proto3" json:"damage,omitempty"`
	CurrentHp     int32                  `protobuf:"varint,3,opt,name=current_hp,json=currentHp,proto3" json:"current_hp,omitempty"`
	MaxHp         int32                  `protobuf:"varint,4,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	IsDead        bool                   `protobuf:"varint,5,opt,name=is_dead,json=isDead,proto3" json:"is_dead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeUpdatePush) Reset() {
	*x = AttributeUpdatePush{}
	mi := &file_protocol_game_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeUpdatePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeUpdatePush) ProtoMessage() {}

func (x *AttributeUpdatePush) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeUpdatePush.ProtoReflect.Descriptor instead.
func (*AttributeUpdatePush) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{23}
}

func (x *AttributeUpdatePush) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *AttributeUpdatePush) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *AttributeUpdatePush) GetCurrentHp() int32 {
	if x != nil {
		return x.CurrentHp
	}
	return 0
}

func (x *AttributeUpdatePush) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *AttributeUpdatePush) GetIsDead() bool {
	if x != nil {
		return x.IsDead
	}
	return false
}

type PlayerDeadPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	KillerId      string                 `protobuf:"bytes,2,opt,name=killer_id,json=killerId,proto3" json:"killer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerDeadPush) Reset() {
	*x = PlayerDeadPush{}
	mi := &file_protocol_game_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerDeadPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDeadPush) ProtoMessage() {}

func (x *PlayerDeadPush) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDeadPush.ProtoReflect.Descriptor instead.
func (*PlayerDeadPush) Descriptor() ([]byte, []int) {
	return file_protocol_game_proto_rawDescGZIP(), []int{24}
}

func (x *PlayerDeadPush) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerDeadPush) GetKillerId() string {
	if x != nil {
		return x.KillerId
	}
	return ""
}

var File_protocol_game_proto protoreflect.FileDescriptor

const file_protocol_game_proto_rawDesc = "" +
	"\n" +
	"\x13protocol/game.proto\x12\bprotocol\"H\n" +
	"\x11CreateRoomRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vmax_players\x18\x02 \x01(\x05R\n" +
	"maxPlayers\"8\n" +
	"\x12CreateRoomResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x12\n" +
	"\x10ListRoomsRequest\"V\n" +
	"\bRoomInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\x10\n" +
	"\x03max\x18\x04 \x01(\x05R\x03max\"=\n" +
	"\x11ListRoomsResponse\x12(\n" +
	"\x05rooms\x18\x01 \x03(\v2\x12.protocol.RoomInfoR\x05rooms\":\n" +
	"\vJoinRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"U\n" +
	"\fJoinResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\"\x0e\n" +
	"\fLeaveRequest\"=\n" +
	"\rLeaveResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"3\n" +
	"\aVector3\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\"D\n" +
	"\n" +
	"Quaternion\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\x12\f\n" +
	"\x01w\x18\x04 \x01(\x02R\x01w\"~\n" +
	"\vPlayerState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\bposition\x18\x02 \x01(\v2\x11.protocol.Vector3R\bposition\x120\n" +
	"\brotation\x18\x03 \x01(\v2\x14.protocol.QuaternionR\brotation\"\xd0\x01\n" +
	"\vMoveRequest\x12-\n" +
	"\bposition\x18\x01 \x01(\v2\x11.protocol.Vector3R\bposition\x120\n" +
	"\brotation\x18\x02 \x01(\v2\x14.protocol.QuaternionR\brotation\x12\x14\n" +
	"\x05speed\x18\x03 \x01(\x02R\x05speed\x12\x1f\n" +
	"\vis_grounded\x18\x04 \x01(\bR\n" +
	"isGrounded\x12)\n" +
	"\x10client_timestamp\x18\x05 \x01(\x03R\x0fclientTimestamp\"k\n" +
	"\fMoveResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\bposition\x18\x03 \x01(\v2\x11.protocol.Vector3R\bposition\"D\n" +
	"\vChatMessage\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"4\n" +
	"\x0ePlayerJoinPush\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"!\n" +
	"\x0fPlayerLeavePush\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb8\x01\n" +
	"\x0ePlayerMovePush\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\bposition\x18\x02 \x01(\v2\x11.protocol.Vector3R\bposition\x120\n" +
	"\brotation\x18\x03 \x01(\v2\x14.protocol.QuaternionR\brotation\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x02R\x05speed\x12\x1f\n" +
	"\vis_grounded\x18\x05 \x01(\bR\n" +
	"isGrounded\"t\n" +
	"\x11ForcePositionPush\x12-\n" +
	"\bposition\x18\x01 \x01(\v2\x11.protocol.Vector3R\bposition\x120\n" +
	"\brotation\x18\x02 \x01(\v2\x14.protocol.QuaternionR\brotation\"\x92\x01\n" +
	"\tSkillInfo\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\x05R\askillId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12/\n" +
	"\tdirection\x18\x03 \x01(\v2\x11.protocol.Vector3R\tdirection\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"F\n" +
	"\x10CastSkillRequest\x122\n" +
	"\n" +
	"skill_info\x18\x01 \x01(\v2\x13.protocol.SkillInfoR\tskillInfo\"G\n" +
	"\x11CastSkillResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"`\n" +
	"\rSkillCastPush\x12\x1b\n" +
	"\tcaster_id\x18\x01 \x01(\tR\bcasterId\x122\n" +
	"\n" +
	"skill_info\x18\x02 \x01(\v2\x13.protocol.SkillInfoR\tskillInfo\"\x99\x01\n" +
	"\x13AttributeUpdatePush\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12\x16\n" +
	"\x06damage\x18\x02 \x01(\x05R\x06damage\x12\x1d\n" +
	"\n" +
	"current_hp\x18\x03 \x01(\x05R\tcurrentHp\x12\x15\n" +
	"\x06max_hp\x18\x04 \x01(\x05R\x05maxHp\x12\x17\n" +
	"\ais_dead\x18\x05 \x01(\bR\x06isDead\"=\n" +
	"\x0ePlayerDeadPush\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tkiller_id\x18\x02 \x01(\tR\bkillerIdB\x16Z\x14game-server/protocolb\x06proto3"

var (
	file_protocol_game_proto_rawDescOnce sync.Once
	file_protocol_game_proto_rawDescData []byte
)

func file_protocol_game_proto_rawDescGZIP() []byte {
	file_protocol_game_proto_rawDescOnce.Do(func() {
		file_protocol_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_game_proto_rawDesc), len(file_protocol_game_proto_rawDesc)))
	})
	return file_protocol_game_proto_rawDescData
}

var file_protocol_game_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_protocol_game_proto_goTypes = []any{
	(*CreateRoomRequest)(nil),   // 0: protocol.CreateRoomRequest
	(*CreateRoomResponse)(nil),  // 1: protocol.CreateRoomResponse
	(*ListRoomsRequest)(nil),    // 2: protocol.ListRoomsRequest
	(*RoomInfo)(nil),            // 3: protocol.RoomInfo
	(*ListRoomsResponse)(nil),   // 4: protocol.ListRoomsResponse
	(*JoinRequest)(nil),         // 5: protocol.JoinRequest
	(*JoinResponse)(nil),        // 6: protocol.JoinResponse
	(*LeaveRequest)(nil),        // 7: protocol.LeaveRequest
	(*LeaveResponse)(nil),       // 8: protocol.LeaveResponse
	(*Vector3)(nil),             // 9: protocol.Vector3
	(*Quaternion)(nil),          // 10: protocol.Quaternion
	(*PlayerState)(nil),         // 11: protocol.PlayerState
	(*MoveRequest)(nil),         // 12: protocol.MoveRequest
	(*MoveResponse)(nil),        // 13: protocol.MoveResponse
	(*ChatMessage)(nil),         // 14: protocol.ChatMessage
	(*PlayerJoinPush)(nil),      // 15: protocol.PlayerJoinPush
	(*PlayerLeavePush)(nil),     // 16: protocol.PlayerLeavePush
	(*PlayerMovePush)(nil),      // 17: protocol.PlayerMovePush
	(*ForcePositionPush)(nil),   // 18: protocol.ForcePositionPush
	(*SkillInfo)(nil),           // 19: protocol.SkillInfo
	(*CastSkillRequest)(nil),    // 20: protocol.CastSkillRequest
	(*CastSkillResponse)(nil),   // 21: protocol.CastSkillResponse
	(*SkillCastPush)(nil),       // 22: protocol.SkillCastPush
	(*AttributeUpdatePush)(nil), // 23: protocol.AttributeUpdatePush
	(*PlayerDeadPush)(nil),      // 24: protocol.PlayerDeadPush
}
var file_protocol_game_proto_depIdxs = []int32{
	3,  // 0: protocol.ListRoomsResponse.rooms:type_name -> protocol.RoomInfo
	9,  // 1: protocol.PlayerState.position:type_name -> protocol.Vector3
	10, // 2: protocol.PlayerState.rotation:type_name -> protocol.Quaternion
	9,  // 3: protocol.MoveRequest.position:type_name -> protocol.Vector3
	10, // 4: protocol.MoveRequest.rotation:type_name -> protocol.Quaternion
	9,  // 5: protocol.MoveResponse.position:type_name -> protocol.Vector3
	9,  // 6: protocol.PlayerMovePush.position:type_name -> protocol.Vector3
	10, // 7: protocol.PlayerMovePush.rotation:type_name -> protocol.Quaternion
	9,  // 8: protocol.ForcePositionPush.position:type_name -> protocol.Vector3
	10, // 9: protocol.ForcePositionPush.rotation:type_name -> protocol.Quaternion
	9,  // 10: protocol.SkillInfo.direction:type_name -> protocol.Vector3
	19, // 11: protocol.CastSkillRequest.skill_info:type_name -> protocol.SkillInfo
	19, // 12: protocol.SkillCastPush.skill_info:type_name -> protocol.SkillInfo
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_protocol_game_proto_init() }
func file_protocol_game_proto_init() {
	if File_protocol_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_game_proto_rawDesc), len(file_protocol_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_game_proto_goTypes,
		DependencyIndexes: file_protocol_game_proto_depIdxs,
		MessageInfos:      file_protocol_game_proto_msgTypes,
	}.Build()
	File_protocol_game_proto = out.File
	file_protocol_game_proto_goTypes = nil
	file_protocol_game_proto_depIdxs = nil
}
